-- CRIAÇÃO DO SCRIPT DE VERSIONAMENTO DA TABELA 'CATEGORIA' DE INSERÇÃO DE CARGA

INSERT INTO TB_CATEGORIA (id, nome) VALUES(1,'Limpeza');
INSERT INTO TB_CATEGORIA (id, nome) VALUES(2,'Higiene');
INSERT INTO TB_CATEGORIA (id, nome) VALUES(3,'Laticínio');
INSERT INTO TB_CATEGORIA (id, nome) VALUES(4,'Frios');
INSERT INTO TB_CATEGORIA (id, nome) VALUES(5,'Massas');
INSERT INTO TB_CATEGORIA (id, nome) VALUES(6,'Higiene Pessoal');
INSERT INTO TB_CATEGORIA (id, nome) VALUES(7,'Papelaria');
INSERT INTO TB_CATEGORIA (id, nome) VALUES(8,'Hortifrutas');
INSERT INTO TB_CATEGORIA (id, nome) VALUES(9,'Carnes');
INSERT INTO TB_CATEGORIA (id, nome) VALUES(10,'Bebidas');
INSERT INTO TB_CATEGORIA (id, nome) VALUES(11,'Doces');
INSERT INTO TB_CATEGORIA (id, nome) VALUES(12,'Pescados');
INSERT INTO TB_CATEGORIA (id, nome) VALUES(13,'Padaria');
