-- CRIAÇÃO DO SCRIPT DE VERSIONAMENTO DA TABELA 'PRODUTO'

CREATE TABLE IF NOT EXISTS TB_PRODUTO (
id INTEGER PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(40) not null,
descricao VARCHAR(50) null,
preco DECIMAL(19,2) not null default 0,
data_cadastro DATE not null,
categoria_id INTEGER not null,
primary key (id)
);

-- ADICIONANDO A CONSTRAINT
ALTER TABLE TB_PRODUTO ADD FOREIGN KEY (CATEGORIA_ID) REFERENCES TB_CATEGORIA(ID);

