-- CRIAÇÃO DO SCRIPT DE VERSIONAMENTO DA TABELA 'PEDIDO'
-- @autor: Emanuel Gabriel Sousa

CREATE TABLE IF NOT EXISTS TB_PEDIDO (
id INTEGER PRIMARY KEY AUTO_INCREMENT,
descricao VARCHAR(100) NOT NULL,
valor_total DECIMAL(19,2) NOT NULL default 0,
data_pedido DATE NOT NULL, 
primary key (id)
);

-- ADICIONANDO A CONSTRAINT/RESTRIÇÕES
--ALTER TABLE TB_PEDIDO ADD FOREIGN KEY (CATEGORIA_ID) REFERENCES TB_CATEGORIA(ID);

