-- CRIAÇÃO DO SCRIPT DE VERSIONAMENTO DA TABELA 'ITENS_PEDIDO'
-- @autor: Emanuel Gabriel Sousa

CREATE TABLE IF NOT EXISTS TB_ITENS_PEDIDO (
id INTEGER PRIMARY KEY AUTO_INCREMENT,
preco_unitario DECIMAL(19,2) NOT NULL DEFAULT 0,
quantidade INTEGER NOT NULL DEFAULT 0,
data_pedido DATE NOT NULL,
pedido_id INTEGER NOT NULL,
produto_id INTEGER NOT NULL,
primary key (id)
);



-- ADICIONANDO A CONSTRAINT/RESTRIÇÕES - TABELA 'TB_PEDIDO' E TABELA 'TB_PRODUTO'
ALTER TABLE TB_ITENS_PEDIDO ADD FOREIGN KEY (PEDIDO_ID) REFERENCES TB_PEDIDO(ID);
ALTER TABLE TB_ITENS_PEDIDO ADD FOREIGN KEY (PRODUTO_ID) REFERENCES TB_PRODUTO(ID);

